spring:
  application:
    name: match

  profiles:
    active: local

logging:
  level:
    reactor.netty.http.server.HttpServer: WARN
    org.springframework.web.reactive: WARN
    com:
      jinjin99:
        sketch: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    enable:
      all: true
  endpoint:
    prometheus:
      enabled: true
